export const QUERY_KEY = {
  MESSAGES: "MESSAGES",
  SUMAJOB_STAFF: "SUMAJOB_STAFF",
  NEWS: "NEWS",
  MESSAGE_DETAIL: "MESSAGE_DETAIL",
  NEWS_DETAIL: "NEWS_DETAIL",
  PREFS: "PREFS",
  JOBS: "JOBS",
  //MST
  BUSINESSES: "BUSINESSES",
  CONDITIONS: "CONDITIONS",

  BANNER_HOME: "BANNER_HOME",
  JOB_DETAIL: "JOB_DETAIL",
};
